import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import 'react-bootstrap-range-slider/dist/react-bootstrap-range-slider.css';
import RangeSlider from 'react-bootstrap-range-slider';

export default function Home() {
  const [purchase, setPurchase] = useState(300000);
  const [down, setDown] = useState(60000);
  const [repayment, setRepayment] = useState(30);
  const [interest, setInterest] = useState(3.8);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Mortgage Calculator
        </h1>

        <p className={styles.description}>
          Get started estimating your monthly payments
        </p>

        <div className={styles.mortgage}>
          <div id="purchase">
            <p>Purchase Price</p>
            <label htmlFor="">${(Math.round(purchase*100)/100).toLocaleString()}</label>
            <RangeSlider 
            value ={purchase}
            onChange ={changeEvent => setPurchase(changeEvent.target.value)}
            min={200000}
            max={1000000}
            step={50000}
            />
          </div>

          <div id="down">
          <p>Down Payment</p>
            <label htmlFor="">${(Math.round(down*100)/100).toLocaleString()}</label>
            <RangeSlider 
            value ={down}
            onChange ={changeEvent => setDown(changeEvent.target.value)}
            min={30000}
            max={200000}
            step={10000}
            />
          </div>
          <div id="repayment">
            <p>Repayment</p>
              <label htmlFor="">{repayment} years</label>
              <RangeSlider 
              value ={repayment}
              onChange ={changeEvent => setRepayment(changeEvent.target.value)}
              min={1}
              max={50}
              step={1}
              />
          </div>

          <div id="interest">
            <p>interest</p>
              <label htmlFor="">{interest}%</label>
              <RangeSlider 
              value ={interest}
              onChange ={changeEvent => setInterest(changeEvent.target.value)}
              min={0}
              max={30}
              step={.1}
              />
          </div>
          <div id="loan-amount">
            Loan Amount
            ${(Math.round((purchase-down)*100)/100).toLocaleString()}
          </div>
          <div id="per-month">
            Per Month 
             ${(Math.round(((purchase-down)/(repayment*12))*100)/100).toLocaleString()}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
